name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    runs-on: ubuntu-22.04
    strategy: 
      matrix:
        version: ['3.8', '3.9']
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          python-version: ${{matrix.version}}
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        id: run-py-test-id
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project tests
      - name: upload test reports
        if: failure() && steps.run-py-test-id.outcome == 'failure'
        # failure()是判断覆盖前面的每一步的检查，step id 是判断该 id 的 failure
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: htmlcov/
  
  deploy:
    runs-on: ubuntu-22.04
    if: success()
    # if: ${{ always()}}
    # if: ${{ failure()}}
    needs: test-code
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: deploy code
        run: echo "deploy........."